apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/
  - argocd/
  - apisix/

commonLabels:
  app.kubernetes.io/managed-by: devopszon
  app.kubernetes.io/name: pim-ingestor-api

patchesStrategicMerge:
  - argocd/patches.yaml
  - apisix/patches.yaml