---
# Apisix Application Template (Updated)
# Bu şablon, yeni deploy edilecek uygulamalar için Apisix Route kaynağını oluşturur.
# Şablon, trafiği doğrudan ilgili Kubernetes Service'ine yönlendirir.
#
# Template parametreleri:
# pim-ingestor-api - Uygulama ve Route adı için kullanılır
# partvendo - Uygulamanın bulunduğu namespace
# 8080 - Kubernetes Service portu
# devopszon.com - Erişilecek host adı (örn: devopszon.com)
# /api/pim-ingestor-api - Erişilecek path (örn: /api/benim-uygulamam)
# pim-ingestor-api - Hedef Kubernetes Service'in adı

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: pim-ingestor-api-route
  namespace: partvendo
spec:
  http:
  - name: pim-ingestor-api-rule
    match:
      hosts:
      - devopszon.com
      paths:
      # DİKKAT: Path'in sonuna "/*" eklenmesi, alt yolların da yakalanmasını sağlar.
      # Örneğin /api/app/* -> /api/app/login, /api/app/users gibi tüm istekleri karşılar.
      - /api/pim-ingestor-api/*
    backends:
    # Trafik doğrudan Kubernetes Service'ine yönlendiriliyor.
    # ApisixUpstream veya ApisixService kaynağına gerek yoktur.
    - serviceName: pim-ingestor-api
      servicePort: 8080
      weight: 100
    plugins:
    # CORS (Cross-Origin Resource Sharing) ayarları
    - name: cors
      enable: true
      config:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "*"
    # Gelen isteğin path'ini yeniden yazarak servise doğru iletilmesini sağlar.
    # Örneğin: devopszon.com/api/app/login -> app-servisi:80/login
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/api/pim-ingestor-api/(.*)", "/$1"]