apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: partvendo
  name: pim-ingestor-api
  labels:
    app: pim-ingestor-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: pim-ingestor-api
  template:
    metadata:
      labels:
        app: pim-ingestor-api
        service: pim-ingestor-api
      annotations:
        vault.hashicorp.com/agent-inject: 'false'
    spec:
      serviceAccountName: pim-ingestor-api
      
      containers:
        - name: pim-ingestor-api
          image: registry.partvendo.xyz/partvendo/pim-ingestor-api:v1.0.26
          command: ["/bin/bash", "-c"]
          args:
            - |
              exec dotnet Pim.Ingestor.API.dll
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m     
          
                   